server:
  port: 8080

orientdb:
  connectionString: plocal:/home/bipedal/data/sb-notebook/orient
  user: admin
  password: admin

file-store:
  protocol: file
  base-path: /home/bipedal/data/sb-notebook/files

---
spring:
  profiles: test


orientdb:
  connectionString: memory:test
  user: admin
  password: admin

file-store:
  protocol: file
  base-path: /tmp/test